# ----------------------------
# Makefile Options
# ----------------------------

NAME = galaxis
DESCRIPTION = "Ag C Agon glaxis"
COMPRESSED = NO

HEADERS = headers

CFLAGS = -Wall -Wextra -Oz -Wint-conversion
CXXFLAGS = -Wall -Wextra -Oz -Wint-conversion

# ----------------------------

include $(shell cedev-config --makefile)
