# ----------------------------
# Makefile Options
# ----------------------------

NAME = journey
DESCRIPTION = "Ag C simple journey"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
