# ----------------------------
# Makefile Options
# ----------------------------

NAME = abird
DESCRIPTION = "Ag C ASCII bird"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
