# ----------------------------
# Makefile Options
# ----------------------------

NAME = UE14500-Emu
DESCRIPTION = "Ag C Agon UE14500 Emulator"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz -Wint-conversion
CXXFLAGS = -Wall -Wextra -Oz -Wint-conversion

# ----------------------------

include $(shell cedev-config --makefile)
