# ----------------------------
# Makefile Options
# ----------------------------

NAME = flagon
DESCRIPTION = "Ag C Agon flappy bird"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
