# ----------------------------
# Makefile Options
# ----------------------------

NAME = ant
DESCRIPTION = "Ag C Agon Langton ant"
COMPRESSED = NO

HEADERS = headers

CFLAGS = -Wall -Wextra -Oz -Wint-conversion
CXXFLAGS = -Wall -Wextra -Oz -Wint-conversion

# ----------------------------

include $(shell cedev-config --makefile)
