# ----------------------------
# Makefile Options
# ----------------------------

NAME = awar
DESCRIPTION = "Ag C apple war"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
