# ----------------------------
# Makefile Options
# ----------------------------

NAME = ue14500-asm
DESCRIPTION = "Ag C ue14500 assembler"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
