# ----------------------------
# Makefile Options
# ----------------------------

NAME = flappy
DESCRIPTION = "Ag C cursed flappy"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
